// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv0U6XZRB1ZUtU6yM5gKWV9af2JzXnO4M',
    appId: '1:838454593429:web:6240bea4127cf8af29989c',
    messagingSenderId: '838454593429',
    projectId: 'evently-c18-bdb0b',
    authDomain: 'evently-c18-bdb0b.firebaseapp.com',
    storageBucket: 'evently-c18-bdb0b.firebasestorage.app',
    measurementId: 'G-77612K2RMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSbgtbkezNSopepv-sm0q6fZ0HlfSsZys',
    appId: '1:838454593429:android:036c2de0b7b153f029989c',
    messagingSenderId: '838454593429',
    projectId: 'evently-c18-bdb0b',
    storageBucket: 'evently-c18-bdb0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDut8r-OarlbJjC6rV83YCp46k1EVpj7bM',
    appId: '1:838454593429:ios:a5f48fa83904665829989c',
    messagingSenderId: '838454593429',
    projectId: 'evently-c18-bdb0b',
    storageBucket: 'evently-c18-bdb0b.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC18',
  );

}