// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyLKt769jS8QyPMJBr6QswIVzzWdGjTc4',
    appId: '1:781836381973:web:c1419e39894fa2edcdc31c',
    messagingSenderId: '781836381973',
    projectId: 'evently-c18-57dc0',
    authDomain: 'evently-c18-57dc0.firebaseapp.com',
    storageBucket: 'evently-c18-57dc0.firebasestorage.app',
    measurementId: 'G-LJN5L7DBC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8mlM-ynjzxld_3h1eXj9jmT08u9jEY3E',
    appId: '1:781836381973:android:37d72984c8783f5bcdc31c',
    messagingSenderId: '781836381973',
    projectId: 'evently-c18-57dc0',
    storageBucket: 'evently-c18-57dc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvKRpBPzsIJO7JqZjhKmEqSjY3Quze6jA',
    appId: '1:781836381973:ios:f6505d427986403ccdc31c',
    messagingSenderId: '781836381973',
    projectId: 'evently-c18-57dc0',
    storageBucket: 'evently-c18-57dc0.firebasestorage.app',
    iosBundleId: 'com.example.eventlyC18',
  );

}